version: '3.8'

services:
  app:
    image: demo
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 181202
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Если нужно автоматическое создание таблиц

  db:
    image: postgres:14.7-alpine
    restart: always
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 181202
      POSTGRES_DB: paper
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: